### ISSUE TITLE
"Organize Favorites" -> "Export to A File" results in crash

### ISSUE THREAD

**Issue by ahake** [Terminals-Origin/Terminals#1]
This is the log dump:
INFO  2017-04-07 14:47:45,324   169ms Terminals              Main               - -------------------------------Title: Terminals 4.0.0 started Version:4.0.0.41829 Date:2/04/2017 10:14:19 AM-------------------------------
INFO  2017-04-07 14:47:45,368   214ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2017-04-07 14:47:45,370   215ms Terminals              gGeneralProperties - CommandLine:"C:\Program Files (x86)\Terminals\Terminals.exe" 
INFO  2017-04-07 14:47:45,370   216ms Terminals              gGeneralProperties - CurrentDirectory:C:\Program Files (x86)\Terminals
INFO  2017-04-07 14:47:45,371   216ms Terminals              gGeneralProperties - MachineName:ANDYS
INFO  2017-04-07 14:47:45,371   216ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.2.9200.0
INFO  2017-04-07 14:47:45,371   217ms Terminals              gGeneralProperties - ProcessorCount:4
INFO  2017-04-07 14:47:45,371   217ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2017-04-07 14:47:45,372   217ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2017-04-07 14:47:45,372   218ms Terminals              gGeneralProperties - WorkingSet:23719936
INFO  2017-04-07 14:47:45,372   218ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2017-04-07 14:47:45,373   218ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2017-04-07 14:47:45,373   218ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2017-04-07 14:47:45,374   219ms Terminals              Main               - Start state 3 Complete: Set application properties
INFO  2017-04-07 14:47:45,419   264ms Terminals              Main               - Start state 4 Complete: Parse command line
INFO  2017-04-07 14:47:45,420   266ms Terminals              Main               - Start state 5 Complete: User account control
INFO  2017-04-07 14:47:45,421   266ms Terminals              Main               - Start state 6 Complete: Set Single instance mode
INFO  2017-04-07 14:47:45,540   386ms Terminals              Main               - Start state 7 Complete: Initilizing Persistence
INFO  2017-04-07 14:47:45,542   388ms Terminals              Main               - Start state 8 Complete: Configuration upgrade
INFO  2017-04-07 14:47:45,544   389ms Terminals              TryLoadFile        - Loading History from: C:\Users\andy.hake\AppData\Local\Robert_Chartier\Terminals\Data\History.xml
FATAL 2017-04-07 14:47:55,691 10536ms Terminals              howApplicationExit - System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminals.Forms.Controls.FavoriteTreeNode.UpdateByFavorite(IFavorite favorite, String toolTip)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNode(IFavorite favorite, Int32 index)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNodes(IEnumerable`1 favorites)
   at Terminals.Forms.ExportForm..ctor(IPersistence persistence, ConnectionManager connectionManager, FavoriteIcons favoriteIcons)
   at Terminals.OrganizeFavoritesForm.ExportToFileToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2017-04-07 14:47:55,693 10538ms Terminals              howApplicationExit - Application has to be terminated.

**Comment by TheOoze777** [comment]
I can confirm this issue.

**Comment by tardis4500** [comment]
I can confirm this also.

**Comment by cgtracy** [comment]
Also confirmed.  And annoying. =)

**Comment by ahake** [comment]
Thank you, Jirka

**Comment by kendoori** [comment]
Newbie question... when you guys close a case like this and add the commits, how does one get the fixed version?

**Comment by jirkapok** [comment]
Good question (but not related to this issue), developer guide describes process used at CodePlex, since we moved, there will be other process on github, which wasnt defined yet.

**Comment by ehuggz** [comment]
I am still crashing when exporting after pulling Master and compiling - even though GitHub shows this bug is fixed. Is there any more information on the new process for getting updates from GitHub.

**Comment by jirkapok** [comment]
I will upgrade the developer guide, the fix will be published with next version, e.g. the fix is not published in current 4,0 release.
