### ISSUE TITLE
Mouse pointer disappers in RDP client sessions

### ISSUE THREAD

**Issue by digitalnomadjc** [Terminals-Origin/Terminals#104]
In RDP sessions my mouse pointer disappears any time I move over the text box area of an application.
It is reproducible in:
- Notepad
- WordPad
- PowerShell ISE

**Comment by tntvenion** [comment]
The same problem is described in this issue: https://github.com/Terminals-Origin/Terminals/issues/2
I still have the same problem. But there is currently a way to avoid it (at least it works for me, on two different PCs): the problem only happens after a cold boot. I restart my PC and the problem does not appear until I shut it down and boot up again. Some windows update has made it that way. This problem appeared in win 1703 creators update with monitors that need scaling and there was no workaround.

**Comment by PaddyBudz** [comment]
You can use the workaround of changing the mouse scheme to black.

**Comment by digitalnomadjc** [comment]
Thanks for your help :)

**Comment by stevebanik-ndsc** [comment]
Confirmed @PaddyBudz  workaround (changing mouse scheme to black)

**Comment by Chunlong101** [comment]
Thanks for letting me know the workaround~
