### ISSUE TITLE
Empty path is illegal on windows

### ISSUE THREAD

**Issue by cloorc** [Terminals-Origin/Terminals#118]
I'm using windows 10 1709 release and fresh installed terminals 4.0.1. When I'm trying to connect to my SSH virtual machine in virtualbox, it tells me like this:

![image](https://user-images.githubusercontent.com/13597105/31932458-f11d1c8c-b8d8-11e7-9e47-791ee2b7bd24.png)

The property of this connection is as fowllowing:

![image](https://user-images.githubusercontent.com/13597105/31932435-e4f67228-b8d8-11e7-9596-79741d0eae34.png)

**Comment by jirkapok** [comment]
Can you provide log files?

**Comment by cloorc** [comment]
INFO  2017-10-26 09:43:02,702   106ms Terminals              Main               - -------------------------------Title: Terminals 4.0.1 started Version:4.0.1.16210 Date:2017/6/24 17:00:22-------------------------------
INFO  2017-10-26 09:43:02,735   139ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2017-10-26 09:43:02,738   142ms Terminals              gGeneralProperties - CommandLine:"C:\Users\z0228\Apps\Terminals\Terminals.exe" 
INFO  2017-10-26 09:43:02,740   144ms Terminals              gGeneralProperties - CurrentDirectory:C:\Users\z0228\Apps\Terminals
INFO  2017-10-26 09:43:02,742   146ms Terminals              gGeneralProperties - MachineName:Z0228
INFO  2017-10-26 09:43:02,744   148ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.2.9200.0
INFO  2017-10-26 09:43:02,746   150ms Terminals              gGeneralProperties - ProcessorCount:8
INFO  2017-10-26 09:43:02,748   152ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2017-10-26 09:43:02,750   154ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2017-10-26 09:43:02,751   155ms Terminals              gGeneralProperties - WorkingSet:27090944
INFO  2017-10-26 09:43:02,753   157ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2017-10-26 09:43:02,755   159ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2017-10-26 09:43:02,757   161ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2017-10-26 09:43:02,761   165ms Terminals              Main               - Start state 3 Complete: Set application properties
INFO  2017-10-26 09:43:02,818   222ms Terminals              Main               - Start state 4 Complete: Parse command line
INFO  2017-10-26 09:43:02,821   225ms Terminals              Main               - Start state 5 Complete: User account control
INFO  2017-10-26 09:43:02,822   226ms Terminals              Main               - Start state 6 Complete: Set Single instance mode
INFO  2017-10-26 09:43:02,957   360ms Terminals              Main               - Start state 7 Complete: Initilizing Persistence
INFO  2017-10-26 09:43:02,959   362ms Terminals              TryLoadFile        - Loading History from: C:\Users\z0228\AppData\Local\Robert_Chartier\Terminals\Data\History.xml
INFO  2017-10-26 09:43:02,959   362ms Terminals              Main               - Start state 8 Complete: Configuration upgrade
ERROR 2017-10-26 09:43:03,425   829ms Terminals              Register           - Error accessing registry
System.UnauthorizedAccessException: 对注册表项“HKEY_CLASSES_ROOT\TRM”的访问被拒绝。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   在 Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   在 Terminals.ProtocolHandler.CreateTrmRegistrySubKey()
   在 Terminals.ProtocolHandler.Register()
INFO  2017-10-26 09:43:06,085  3489ms Terminals              SaveHistory        - History saved. Duration:30 ms
INFO  2017-10-26 09:43:06,127  3531ms Terminals              Connect            - Connecting to a SSH Connection
FATAL 2017-10-26 09:43:06,334  3738ms Terminals              Connect            - Connecting to unknown Connection
System.ArgumentException: 空路径名是非法的。
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   在 Granados.SSH2.SSH2Connection.UserAuth()
   在 Granados.SSH2.SSH2Connection.Connect()
   在 Granados.SSHConnection.ConnectMain(SSHConnectionParameter param, ISSHConnectionEventReceiver receiver, VersionExchangeHandler pnh, AbstractGranadosSocket s)
   在 SSHClient.Protocol.Connect(Socket s)
   在 Terminals.Connections.TerminalConnection.ConfigureSshConnection(IGuardedSecurity security)
   在 Terminals.Connections.TerminalConnection.Connect()
INFO  2017-10-26 09:43:28,586 25989ms Terminals              Main               - -------------------------------Terminals 4.0.1 Stopped-------------------------------
INFO  2017-10-26 09:43:33,822    93ms Terminals              Main               - -------------------------------Title: Terminals 4.0.1 started Version:4.0.1.16210 Date:2017/6/24 17:00:22-------------------------------
INFO  2017-10-26 09:43:33,851   123ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2017-10-26 09:43:33,854   126ms Terminals              gGeneralProperties - CommandLine:"C:\Users\z0228\Apps\Terminals\Terminals.exe" 
INFO  2017-10-26 09:43:33,856   128ms Terminals              gGeneralProperties - CurrentDirectory:C:\Users\z0228\Apps\Terminals
INFO  2017-10-26 09:43:33,858   130ms Terminals              gGeneralProperties - MachineName:Z0228
INFO  2017-10-26 09:43:33,859   130ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.2.9200.0
INFO  2017-10-26 09:43:33,861   132ms Terminals              gGeneralProperties - ProcessorCount:8
INFO  2017-10-26 09:43:33,863   134ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2017-10-26 09:43:33,865   136ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2017-10-26 09:43:33,867   138ms Terminals              gGeneralProperties - WorkingSet:26066944
INFO  2017-10-26 09:43:33,869   140ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2017-10-26 09:43:33,870   141ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2017-10-26 09:43:33,872   143ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2017-10-26 09:43:33,874   145ms Terminals              Main               - Start state 3 Complete: Set application properties
INFO  2017-10-26 09:43:33,902   174ms Terminals              Main               - Start state 4 Complete: Parse command line
INFO  2017-10-26 09:43:33,904   175ms Terminals              Main               - Start state 5 Complete: User account control
INFO  2017-10-26 09:43:33,906   177ms Terminals              Main               - Start state 6 Complete: Set Single instance mode
INFO  2017-10-26 09:43:33,940   212ms Terminals              Main               - Start state 7 Complete: Initilizing Persistence
INFO  2017-10-26 09:43:33,942   214ms Terminals              TryLoadFile        - Loading History from: C:\Users\z0228\AppData\Local\Robert_Chartier\Terminals\Data\History.xml
INFO  2017-10-26 09:43:33,942   214ms Terminals              Main               - Start state 8 Complete: Configuration upgrade
INFO  2017-10-26 09:43:35,960  2231ms Terminals              SaveHistory        - History saved. Duration:14 ms
INFO  2017-10-26 09:43:35,976  2247ms Terminals              Connect            - Connecting to a SSH Connection
FATAL 2017-10-26 09:43:36,121  2392ms Terminals              Connect            - Connecting to unknown Connection
System.ArgumentException: 空路径名是非法的。
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   在 Granados.SSH2.SSH2Connection.UserAuth()
   在 Granados.SSH2.SSH2Connection.Connect()
   在 Granados.SSHConnection.ConnectMain(SSHConnectionParameter param, ISSHConnectionEventReceiver receiver, VersionExchangeHandler pnh, AbstractGranadosSocket s)
   在 SSHClient.Protocol.Connect(Socket s)
   在 Terminals.Connections.TerminalConnection.ConfigureSshConnection(IGuardedSecurity security)
   在 Terminals.Connections.TerminalConnection.Connect()
INFO  2017-10-26 09:44:39,075 65347ms Terminals              SaveHistory        - History saved. Duration:7 ms
INFO  2017-10-26 09:44:39,081 65353ms Terminals              Connect            - Connecting to a SSH Connection

**Comment by cloorc** [comment]
Now I think the problem is gone. I realized that I have set my SSH connection to authentication using key pair but I did not provide proper key pairs. When I reached the logging information, I found it declared that it can not access the system registry and then I reopen the terminal as administrator. This time the SSH connection successfully connected. Thanks!
