### ISSUE TITLE
After github move.

### ISSUE THREAD

**Issue by SteveHolle** [Terminals-Origin/Terminals#135]
The link at the bottom of the "Options" menu still points to codeplex.  Is the notification list still maintained?  All I can find is the check box to not be kept up to date.  Has anyone considered automatically detecting new versions?

Thanks for a great project!

**Comment by jirkapok** [comment]
the link will be fixed in next version. The checkbox you mention does exacly what you described. It checks project page for new release, and if there is one, it shows notification popup window.
