### ISSUE TITLE
Terminal emulation falls short of competitors

### ISSUE THREAD

**Issue by kai-uwe-rommel** [Terminals-Origin/Terminals#137]
When I use SSH to a Linux system, the terminal emulation is by far not as capable as that of Putty.
Why don't you simply integrate Putty?

For example, when I use Putty to a Linux system, I automatically get the xterm terminal type and a useful coloring of text. Also with Putty, the Linux SSH session automatically detects its screen height and width from Putty's window size and adapts automatically, when the window size changes.

**Comment by jirkapok** [comment]
putty integration is under active development, see #46 .
