### ISSUE TITLE
Options to customize font

### ISSUE THREAD

**Issue by ck2136** [Terminals-Origin/Terminals#139]
Hi! I couldn't find options to customize the appearance.
If there are please let me know if there isn't it would be good to have! Thanks!

**Comment by jirkapok** [comment]
Which font? What do you want to achieve by changing font?
The only option to change font is for Terminal based connections like ssh or telnet.

**Comment by ck2136** [comment]
Oh I was only talking about customizing fonts for the SSH. Is there an option?

**Comment by jirkapok** [comment]
yes, open the favorite properties and expand the tree with the ssh icon

**Comment by ck2136** [comment]
Thanks!
