### ISSUE TITLE
Empty path is illegal on windows

### ISSUE THREAD

**Issue by bigperson5** [Terminals-Origin/Terminals#145]
I'm using windows 10 release and portable terminals 4.0.1. When I'm trying to connect to my raspbian by SSH I'm getting a error. If I use Putty I can connect without any problem.

I'm starting Terminals as Administrator

Thanks

The log is:

INFO  2017-12-25 12:51:46,090   171ms Terminals              Main               - -------------------------------Title: Terminals 4.0.1 started Version:4.0.1.16210 Date:24/06/2017 11:00:22-------------------------------
INFO  2017-12-25 12:51:46,152   234ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2017-12-25 12:51:46,168   249ms Terminals              gGeneralProperties - CommandLine:"D:\Users\Daniel\Desktop\Terminals_v4.0.1\Terminals.exe" 
INFO  2017-12-25 12:51:46,168   249ms Terminals              gGeneralProperties - CurrentDirectory:D:\Users\Daniel\Desktop\Terminals_v4.0.1
INFO  2017-12-25 12:51:46,168   249ms Terminals              gGeneralProperties - MachineName:CM650
INFO  2017-12-25 12:51:46,168   249ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.1.7601 Service Pack 1
INFO  2017-12-25 12:51:46,168   249ms Terminals              gGeneralProperties - ProcessorCount:8
INFO  2017-12-25 12:51:46,168   249ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2017-12-25 12:51:46,168   249ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2017-12-25 12:51:46,168   249ms Terminals              gGeneralProperties - WorkingSet:24276992
INFO  2017-12-25 12:51:46,168   249ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2017-12-25 12:51:46,168   249ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2017-12-25 12:51:46,168   249ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2017-12-25 12:51:46,168   249ms Terminals              Main               - Start state 3 Complete: Set application properties
INFO  2017-12-25 12:51:46,246   327ms Terminals              Main               - Start state 4 Complete: Parse command line
INFO  2017-12-25 12:51:46,246   327ms Terminals              Main               - Start state 5 Complete: User account control
INFO  2017-12-25 12:51:46,261   343ms Terminals              Main               - Start state 6 Complete: Set Single instance mode
INFO  2017-12-25 12:51:46,386   468ms Terminals              Main               - Start state 7 Complete: Initilizing Persistence
INFO  2017-12-25 12:51:46,386   468ms Terminals              Main               - Start state 8 Complete: Configuration upgrade
INFO  2017-12-25 12:51:46,386   468ms Terminals              TryLoadFile        - Loading History from: D:\Users\Daniel\Desktop\Terminals_v4.0.1\Data\History.xml
INFO  2017-12-25 12:51:49,709  3790ms Terminals              SaveHistory        - History saved. Duration:28 ms
INFO  2017-12-25 12:51:49,724  3806ms Terminals              Connect            - Connecting to a SSH Connection
FATAL 2017-12-25 12:51:49,990  4071ms Terminals              Connect            - Connecting to unknown Connection
System.ArgumentException: No se puede dejar vacío el nombre de la ruta de acceso.
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   en Granados.SSH2.SSH2Connection.UserAuth()
   en Granados.SSH2.SSH2Connection.Connect()
   en Granados.SSHConnection.ConnectMain(SSHConnectionParameter param, ISSHConnectionEventReceiver receiver, VersionExchangeHandler pnh, AbstractGranadosSocket s)
   en SSHClient.Protocol.Connect(Socket s)
   en Terminals.Connections.TerminalConnection.ConfigureSshConnection(IGuardedSecurity security)
   en Terminals.Connections.TerminalConnection.Connect()
INFO  2017-12-25 12:51:52,345  6427ms Terminals              Main               - -------------------------------Terminals 4.0.1 Stopped-------------------------------

**Comment by bandoleritoz** [comment]
Same problem here. We tried this software with a few colleagues and all the ssh connections in all the windows 10 machines received the same error.

**Comment by bandoleritoz** [comment]
![image](https://user-images.githubusercontent.com/35648202/35191032-06b60d8c-fe71-11e7-87c0-267dd17df294.png)
Solved!.

**Comment by bandoleritoz** [comment]
Also if We don't store the passwords there is no way to connect by ssh to any machine.

**Comment by jirkapok** [comment]
we are currently preparing putty integration, see #46.

**Comment by mmm8955405** [comment]
Are you kidding me?  Empty path is illegal on windows10 ！！！  In 2019, the problem still exists.
