### ISSUE TITLE
Can't RDP into Windows Server 2016 using Terminals

### ISSUE THREAD

**Issue by Jason5054** [Terminals-Origin/Terminals#150]
I've setup a new favorite to a new Windows 216 Server in Terminals and am trying to RDP into it using domain admin credentials. Terminals says it's connecting to host and never connects. If I open MSTSC in windows and try to RDP into the server with the same credentials, it works fine. Just not in Terminals. Any idea?

**Comment by jirkapok** [comment]
Did you check security settings like NLA encryption. Also you can have a look into the log files, if you can get more info about the error.

**Comment by Jason5054** [comment]
I checked Enable TLS and NLA Authentication and now I can RDP into it.
