### ISSUE TITLE
Default datePattern in log4net.Appender.RollingFileAppender 

### ISSUE THREAD

**Issue by stevebanik-ndsc** [Terminals-Origin/Terminals#159]
CurrentLog.txt is being rolled to CurrentLog.txtYYYYMMDD per log4net.Appender.RollingFileAppender which causes a Windows prompt asking what program should be used to open a file of type .txtYYYYMMDD.  It would be good to instead roll the file as CurrentLogYYYYMMDD.txt by default so that this prompt doesn't appear.

**Comment by jirkapok** [comment]
fixed in 4856011b3623abde2b9d4d347dea66d27f88115a
