### ISSUE TITLE
Feature Request - window integration

### ISSUE THREAD

**Issue by vmario89** [Terminals-Origin/Terminals#170]
Hey, for some more native view of applications inside Terminals, i would like to see an additional option in the Shortcut Creator to embed programs directly into Terminals. I'd like to use Cmder/ConEmu and other consoles directly in Terminals. This would be a great enhancement.

**Comment by jirkapok** [comment]
The correct solutio is to write custom plugin.
see #94 as example implementation or https://github.com/Terminals-Origin/Terminals/blob/master/Docs/WriteNewPlugin.md
