### ISSUE TITLE
Feature request: Drag and drop to reorder tabs for open sessions

### ISSUE THREAD

**Issue by Bill-Stewart** [Terminals-Origin/Terminals#175]
I tested again. This feature seems to have some interesting behavior/side effects. I have "Show user name in tab title" enabled. Dragging and dropping to reorder tabs only seems to work consistently when 1) I am dragging the active (bold) tab and 2) if my mouse pointer is directly on the favorite (host) name of the tab. It seems not to work consistently (or I don't understand the conditions under which it does not work) when I try to drag a non-active tab or when the mouse pointer is not directly on the favorite name.

**Comment by neumaste** [comment]
Hi,
if I understand this request correctly, this is already working. At least I am able to change the order of the tabs by drag and drop with newest version of Terminals.
If this is what you meant, please retry.

**Comment by Bill-Stewart** [comment]
I tested again. This feature seems to have some interesting behavior/side effects. I have "Show user name in tab title" enabled. Dragging and dropping to reorder tabs only seems to work consistently when 1) I am dragging the active (bold) tab and 2) if my mouse pointer is directly on the favorite (host) name of the tab. It seems not to work consistently (or I don't understand the conditions under which it does not work) when I try to drag a non-active tab or when the mouse pointer is not directly on the favorite name.

**Comment by jirkapok** [comment]
Any issue related to tabs will be fixed by #60
