### ISSUE TITLE
Putty Default Settings needed to stop intermittent disconnects from Unix hosts

### ISSUE THREAD

**Issue by PeterGitHub777** [Terminals-Origin/Terminals#177]
Thank you very much for getting the Putty integration working on later builds but I needed to have the following settings otherwise my Unix hosts would disconnect sessions intermittently. 
When do think it would be released for easy download and install (without compiling code)

Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\Default%20Settings]
"Protocol"="ssh"
"PingInterval"=dword:00000000
"PingIntervalSecs"=dword:0000003b
"SshProt"=dword:00000003

**Comment by jirkapok** [comment]
I am expecting full UI customization of putty options in one of next versions, but for now, there is no plan to change these settings.
Regarding the release, i cant tell.
