### ISSUE TITLE
Feature Request: Unlock Current Session

### ISSUE THREAD

**Issue by twdwyer** [Terminals-Origin/Terminals#178]
I'm really liking this tool! The only issue I'm having is with session timeouts and having to resend the password. The company I work for has implemented a 10min session timeout and have enforced encrypted passwords. So I find myself closing a session that has locked so I can reconnect using the password I have stored. Is there an easy way to just apply the current password to unlock the session without having to close it each time?

**Comment by jirkapok** [comment]
Closing as duplicate with #147
