### ISSUE TITLE
Unable to load plugins

### ISSUE THREAD

**Issue by spacecake** [Terminals-Origin/Terminals#182]
Hi

I tried to update my 3.6.1, even tried switching to a blank 4.0.1.. unable to launch
Got this error [https://pastebin.com/EjDjqmWn](url)

File permission for the current user are full.

Best regards

**Comment by jirkapok** [comment]
The link doesnt work anymore and please provide logs.

**Comment by OverlordQ** [comment]
Link works fine, just copy the link instead of clicking it.

**Comment by keithhopkins-gpc** [comment]
"me too" from Terminals_v4.0.1 on Windows 10

Similar error across several files:
Unable to load plugins from 'C:\bin\Terminals\Plugins\Rdp\Terminals.Plugins.Rdp.dll
Unable to load plugins from 'C:\bin\Terminals\Plugins\Terminal\Terminals.Plugins.Terminal.dll'.
Unable to load plugins from 'C:\bin\Terminals\Plugins\Ica\Terminals.Plugins.Ica.dll'.

System.IO.FileLoadException: Could not load file or assembly 'file:///C:\bin\Terminals\Plugins\Ica\Terminals.Plugins.Ica.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\bin\Terminals\Plugins\Ica\Terminals.Plugins.Ica.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

Google takes me to this explanation: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/loadfromremotesources-element

**Comment by jirkapok** [comment]
This was fixed, see other comments, but i dont remember the issue number.

**Comment by keithhopkins-gpc** [comment]
Looks like Zip Version Crash #89.  I'll try it.
