### ISSUE TITLE
Crashing when highlighting text in SSH session.

### ISSUE THREAD

**Issue by Nicabus** [Terminals-Origin/Terminals#187]
Issue:  When in an SSH session, highlighting/copying text via mouse causes the program to crash as soon as the mouse button is released.

Version: 4.0.1.16210
CommandLine: "C:\Program Files (x86)\Terminals\Terminals.exe" 
CurrentDirectory: C:\Program Files (x86)\Terminals
OSVersion: Microsoft Windows NT 6.2.9200.0
ProcessorCount: 8
UserInteractive: True
Framework Version: 4.0.30319.42000
WorkingSet: 83546112
Is 64bit OS: True
Is 64bit Proces: True

Steps to reproduce:
1. Open SSH to linux system.
2. sudo crontab -l
3. Highlight text via mouse
4. crash - "Terminals has encountered a problem and needs to close..."

[CurrentLog.txt](https://github.com/Terminals-Origin/Terminals/files/2159937/CurrentLog.txt)
[CurrentLog-asAdmin.txt](https://github.com/Terminals-Origin/Terminals/files/2159944/CurrentLog-asAdmin.txt)

Logs attached are with program run normally and as admin.

**Comment by Nicabus** [comment]
Update:  Crash only occurs when highlighting to the edge of the screen.

Can highlight multiple short lines at the same time as long as none hit the edge of screen.

Attached are two screenshots one in which the program crashes when the highlight area hits the edge of the screen, the other one character back from the edge.
![highlightcrash](https://user-images.githubusercontent.com/9196779/42230691-9dfd90c2-7eb7-11e8-96c7-0e2a7fd24fb4.PNG)
![highlight](https://user-images.githubusercontent.com/9196779/42230692-9e084b84-7eb7-11e8-92e5-4d130aead64b.PNG)

**Comment by jirkapok** [comment]
Closing, because of putty integration completely replaces current implementation, see #46.
