### ISSUE TITLE
Terminals Crashes with Export

### ISSUE THREAD

**Issue by PhillyIdol** [Terminals-Origin/Terminals#20]
Basically, I try to export my connections as a backup and I get 'Terminals has encountered a problem and needs to close. Check log files"

Here's what the log says...

FATAL 2017-05-03 15:44:18,485 20760ms Terminals              howApplicationExit - Application has to be terminated

**Comment by HubertusKolster** [comment]
I have the same error

**Comment by jirkapok** [comment]
See also #1 , fix will be delivered with next release.
