### ISSUE TITLE
How to set the order of the favorites toolbar?

### ISSUE THREAD

**Issue by donnyv** [Terminals-Origin/Terminals#203]
I have tried a bunch of things to get the favorites toolbar to be a certain order but can not get it to work. I tried naming them starting with numbers, tried adding them to the toolbar in a certain order and even tried editing the xml file. But nothing seems to stick.

Is there a way to set the order in the favorite toolbar that I'm missing?

**Comment by phozen** [comment]
The treeview sort entry by alphabetic order, starting by the folder name and after by the entry name

**Comment by jirkapok** [comment]
There is also an option how the favorites are sorted. See Options > Interface > Favorites.
Closing as answered.

**Comment by donnyv** [comment]
Ok, than why is this still unsorted?
![image](https://user-images.githubusercontent.com/2224189/55826671-84dba880-5ad6-11e9-86ef-142c82b313e3.png)

**Comment by phozen** [comment]
The sort option is for the side panel, not for the toolbar

**Comment by donnyv** [comment]
Which goes back to my original question.

**Comment by phozen** [comment]
By default, the servers are sorted in the order you add them in the toolbar. If you want to change the order, go on "Favorites" menu > "Organize Favorites Toolbar" and in the new window play with arrow.
