### ISSUE TITLE
dead project ?

### ISSUE THREAD

**Issue by gamersalpha** [Terminals-Origin/Terminals#206]
Hello there, last realease : 

 @jirkapok jirkapok released this on 25 Jun 2017 

no code modificaiton since 1 years, this project have no futur ?

why is very cools

**Comment by jaclas** [comment]
I join to the question? Is alive?

**Comment by jirkapok** [comment]
Yes, there is no one working on it more than one year.
Until find someone else or come back, the PROJECT IS DEAD.

**Comment by gamersalpha** [comment]
O no

 i m using this tools for years

What a bas news !

**Comment by phozen** [comment]
I'm interested to keep this project live, but not sure how many free time I can provide

**Comment by jirkapok** [comment]
write me personal message

**Comment by jirkapok** [comment]
Closing as answered.
