### ISSUE TITLE
Feature Request: Update Window Title With Tab Name

### ISSUE THREAD

**Issue by DaveSchopp** [Terminals-Origin/Terminals#210]
I use [ManicTime Tracker](https://www.manictime.com) for keeping track of time spent on projects and support requests. It captures window titles and the amount of time spent in each window.

Since I connect to multiple servers every day, it would help me track my time if the Terminals window title reflected the tab title.

As it is now, I have to try to manually track my time and when calls start coming in fast and furious, that's difficult to do.

I'm in the process of switching from Remote Desktop Manager, and that was one of the features that initially sold me on that product.

**Comment by phozen** [comment]
Hello DaveSchopp,

After checking the code, I see that this feature already exist in current version. 

To enable it, go to the menu "Tools" > "Options". In the options, choose "Interface" and enable "Show connection information in tool tips" (you can also check "Show full information" if you want more details in the window title.

![change config](https://user-images.githubusercontent.com/17760168/53445877-dbeb5980-3a11-11e9-9813-9a0f1bc19afc.png)

The information are displayed like that:
![after changing config](https://user-images.githubusercontent.com/17760168/53445882-df7ee080-3a11-11e9-9db9-38358da1c56c.png)

Hope that correspond to your expection.

Jérôme

**Comment by jirkapok** [comment]
Yes, closing as answered.
