### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by taemay** [Terminals-Origin/Terminals#230]
With all of the vuls found in the past 3 years in putty, rdp, scp, etc... How secure is terminals at this point?

**Comment by jirkapok** [comment]
Rdp is secure, since it uses currently present system rdp client, so if you have all windows updates, that it is fine.
VNC, telne and ssh were not upgraded, since there was no release since than.
Next version will bring integrated putty, which you will be able to upgrade by your own.
