### ISSUE TITLE
Server timeout

### ISSUE THREAD

**Issue by mdoylellb** [Terminals-Origin/Terminals#236]
After the server times out due to inactivity I get locked out and the log in screen is displayed. In order to log back in I need to manually enter the password. Can you please add an item to the right-click menu for the Connection that when clicked will automatically reconnect the session using the saved password for the connection.

**Comment by Luckyvb** [comment]
i create such functional, but PR i add latter.

**Comment by jirkapok** [comment]
Duplicates #147
