### ISSUE TITLE
Screenshoot's

### ISSUE THREAD

**Issue by blackcrack** [Terminals-Origin/Terminals#24]
Hi,

can you make screenshoot's , because a Picture say's more as 1000 words :)

thank you :)

blacky

**Comment by jirkapok** [comment]
[Features and screenshots](https://github.com/Terminals-Origin/Terminals/blob/master/Docs/Features-and-Screen-shots.md)

**Comment by jirkapok** [comment]
Closing, since there are no more comments.

**Comment by blackcrack** [comment]
👍
