### ISSUE TITLE
show and hide menu for opened servers listed server isn't properly working.

### ISSUE THREAD

**Issue by Asfawh** [Terminals-Origin/Terminals#247]
I have used terminal for some years now and liked it, it's fine on windows so far, but while I use on iMac, it give me hard time to see opened servers tab since this hide menu couldn't figure out how to permanently set that

**Comment by jirkapok** [comment]
There is a plan completely redesign the hiding. Sorry, Your scenario isnt tested anyway.
Closing as wont fix.
