### ISSUE TITLE
visual studio version for building from source

### ISSUE THREAD

**Issue by raceybe** [Terminals-Origin/Terminals#250]
I noticed from commit 97c9724b2f4749a8d84d15cc8d7718891982653e that things were updated for VS 2017, but that was 4 years ago.

Is that still the current working version to load the solution without mass updates to dependencies or libraries?

*edit*
I just found https://github.com/Terminals-Origin/Terminals/blob/master/Docs/Developer-guide.md which indicates this is the case. The reason I'm asking is that I see the SSH libraries seem really out of date so I was hoping that compiling with updates libraries would help resolve that.

**Comment by jirkapok** [comment]
Good point current development is upgraded to VS2022, the rest of upgrades for tooling, packaging and all other concepts follow. See https://github.com/Terminals-Origin/Terminals/commits/46-putty
