### ISSUE TITLE
[FEATURE] - Force Screen Reflow

### ISSUE THREAD

**Issue by robertcaretta** [Terminals-Origin/Terminals#251]
Not sure if this is currently possible, so submitting as a feature request.  I have a very wide monitor and this can often cause problems screensharing with my colleagues. I find that I often need to resize my terminals window prior to screensharing. Unfortunately when I do that my current RDP connections do not resize properly. So I have to disconnect my RDP sessions and reconnect for the windows to look correct prior to screensharing.  I have tried the various display options in Terminals and haven't found a way to make this happen. Would it be possible to add a command to force the screen to re-render/re-flow without having to disconnect the session and re-connet?

**Comment by jirkapok** [comment]
Duplicates #147
