### ISSUE TITLE
Feature Request: Reconnect

### ISSUE THREAD

**Issue by lensoff** [Terminals-Origin/Terminals#31]
Hello, 
I'll allow myself to quote old requests:

1. "After using mRemote, VissionApp and various other apps for several years I have found that Terminals offers the best set of features with the least amount of bugs.

One feature I miss from some of the other apps is a re-connect option on the right-click menu of an RDP tab. This facility is really useful in our domain that has a forced 10min screen lock so effectively just logs the session in again without having to re-key credentials..."

2. "Sometimes when we are connected to one client and after some time without activity, appears the lock window. It is hard to remember all the password and it could be interesting to have the tool/functionality "reconnect" that means send the password to the server instead to open a new session or try to remember the password."

3. "Add the ability to right click and select reconnect from any tab or from any node in the favorites menu. Event if connected sometimes I run into issues with display scaling and copy paste that requ..."

Is it possible to add such functional?

**Comment by pgnewhart** [comment]
I second this request.  I have multiple servers that I connect to and need to completely logout.  If I leave the connection idle, I may have issues since my special server account password expires in 48 hours.  I can only connect and it may open a second connection compounding the issue.

**Comment by Wornell1** [comment]
I add my support to adding this feature.   Being able to right click on the tab and select reconnect would make things much more user friendly.

**Comment by jirkapok** [comment]
Duplicates #147
