### ISSUE TITLE
Crash on Export connections

### ISSUE THREAD

**Issue by meetjaydeep** [Terminals-Origin/Terminals#41]
I'm getting message "Terminals has encountered a problem and needs to close." while exporting the Connections or while Exporting Favourites to file. 
[CurrentLog.txt](https://github.com/Terminals-Origin/Terminals/files/1077921/CurrentLog.txt)

**Comment by mkizer** [comment]
Weird. I just setup a new computer today with Terminals and received the same error on export. The import worked fine though.

**Comment by mkizer** [comment]
Actually, the error that I get on Win 10 is:
System.UnauthorizedAccessException: Access to the registry key 'HKEY_CLASSES_ROOT\TRM' is denied.

Which seems to correspond to an older issue when running as a non-admin account:
https://github.com/Terminals-Origin/Terminals/issues/14

Your particular error is also mentioned in the above thread when running as an admin.

**Comment by jirkapok** [comment]
Duplicates #1 .
