### ISSUE TITLE
When master password is used and password dialog entry is cancelled, terminals still opens!

### ISSUE THREAD

**Issue by kanaifu** [Terminals-Origin/Terminals#5]
This is probably serious security breach - if master password dialog entry is cancelled, terminals app is still opened.
This should not happen.
Also, in this case the startup RDP connections are opened without explicit setting/confirmation/control with the lowest possible display resolution.

**Comment by jirkapok** [comment]
Fixed in 4.0.1

**Comment by truist** [comment]
Was this a security breach? Were stored passwords accessible in prior versions?

**Comment by jirkapok** [comment]
No, it was introduced in 4.0 and fixed in 4.0.1

**Comment by kanaifu** [comment]
Hmm. I didn't check that. I wrote that is a security breach because one could start remote sessions (starting the program itself) without typing the master password - that is going around password-based security.

**Comment by truist** [comment]
OK, thanks for responding. But to be clear: if you canceled out of the dialog, you'd have access to the app, but if you tried to use a host that had a saved password, it wouldn't work?

**Comment by kanaifu** [comment]
I think I worked, but to be sure of it I have to install the first version and try it. Do you need confirmation of this?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by truist** [comment]
My real question is whether it was - or still is - possible to get an unencrypted password without knowing the master password. I expect @jirkapok would have to answer, to be sure. (I've done a little code digging, and it looks like the passwords *are* encrypted with the master password, but I'm not certain.)

**Comment by awojtas** [comment]
Does this mean a hacker could use a 4.0.0 version to access saved credentials, read passwords that are now decrypted in memory, or connect using saved credentials, if they had the db from a terminals install?

**Comment by kanaifu** [comment]
Let me check that in a virtual machine and get back to you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kanaifu** [comment]
I didn’t succeed in finding the 4.0.0 version on github.
Can someone provide the link to the msi/exe?
There are no archived versions there? Maybe on codeplex…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Todor Tanevski<mailto:todor.tanevski@hotmail.com>
Sent: недела, 13 август 2017 06:55
To: Terminals-Origin/Terminals<mailto:reply@reply.github.com>
Subject: RE: [Terminals-Origin/Terminals] When master password is used and password dialog entry is cancelled, terminals still opens! (#5)

Let me check that in a virtual machine and get back to you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kanaifu** [comment]
I guess you wer right about not able to decrypt the passwords from the local file store (am I designating things right?).

I tried the 4.0.0 bytes with my Data.

You could not see the existing passwords, as far as the GUI goes.

See for yourself the attachments, please.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
