### ISSUE TITLE
don't override old setting when updating to new release

### ISSUE THREAD

**Issue by aj3423** [Terminals-Origin/Terminals#52]
I just updated to 4.0.1, I downloaded the zip package Terminals_v4.0.1.zip,  unzip and override the old file, and my old setting and favorites were gone. 
I suggest not override settings when update. (both .msi and .zip)

**Comment by rebork** [comment]
Agreed.  It's pretty frustrating.  I lost all my connections stored up after 2 years upon updating.  

Does anyone know how to get my old connections back?  It feels like I just installed Terminals for the first time...
