### ISSUE TITLE
Terminals 4.0.1 would not start after Update.

### ISSUE THREAD

**Issue by zeiseiwogn** [Terminals-Origin/Terminals#55]
Hello,

after i updating my Terminals to 4.0.1 Terminals would not start.
In the attached Logfile you can see the error.

Please help me
Christian

> INFO  2017-06-30 10:45:50,197   140ms Terminals              Main               - -------------------------------Title: Terminals 4.0.1 started Version:4.0.1.16210 Date:24.06.2017 11:00:22-------------------------------
INFO  2017-06-30 10:45:50,213   155ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2017-06-30 10:45:50,213   155ms Terminals              gGeneralProperties - CommandLine:"C:\Program Files (x86)\Terminals\Terminals.exe" 
INFO  2017-06-30 10:45:50,213   155ms Terminals              gGeneralProperties - CurrentDirectory:C:\Program Files (x86)\Terminals
INFO  2017-06-30 10:45:50,213   155ms Terminals              gGeneralProperties - MachineName:PC-EDVINTERN2
INFO  2017-06-30 10:45:50,213   155ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.1.7601 Service Pack 1
INFO  2017-06-30 10:45:50,213   155ms Terminals              gGeneralProperties - ProcessorCount:4
INFO  2017-06-30 10:45:50,213   155ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2017-06-30 10:45:50,213   155ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2017-06-30 10:45:50,213   155ms Terminals              gGeneralProperties - WorkingSet:21549056
INFO  2017-06-30 10:45:50,213   155ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2017-06-30 10:45:50,213   155ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2017-06-30 10:45:50,213   155ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2017-06-30 10:45:50,213   155ms Terminals              Main               - Start state 3 Complete: Set application properties
FATAL 2017-06-30 10:45:50,228   171ms Terminals              howApplicationExit - System.Configuration.ConfigurationErrorsException: Das Konfigurationssystem konnte nicht initialisiert werden. ---> System.Configuration.ConfigurationErrorsException: Unbekannter Konfigurationsabschnitt "startup". (C:\Program Files (x86)\Terminals\Terminals.exe.Config line 13)
   bei System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   bei System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   bei System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Configuration.ConfigurationManager.PrepareConfigSystem()
   bei System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   bei System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   bei System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   bei System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   bei System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   bei System.Configuration.SettingsBase.get_Item(String propertyName)
   bei System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   bei System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   bei Terminals.Properties.Settings.get_Portable()
   bei Terminals.Configuration.FileLocations.GetDataRootDirectoryFullPath()
   bei Terminals.Configuration.FileLocations.AssignConfigurationFile(String configurationFullPath)
   bei Terminals.Program.ParseCommandline()
   bei Terminals.Program.Main()
FATAL 2017-06-30 10:45:50,228   171ms Terminals              howApplicationExit - Application has to be terminated.

**Comment by LesDee** [comment]
Same problem here.  

The export problem is now fixed but I cannot open any site.

**Comment by jirkapok** [comment]
From which version do you upgrade? Are you able to provide the failing config file.

**Comment by LesDee** [comment]
Upgraded from 3.6.1.  I think there was a forced uninstall of it first.
Where do I find the log?

**Comment by LesDee** [comment]
I did a new download and an install over the top of 3.6.1.
I first made sure Terminals was not running.

Install went OK and all seems to be working fine!

I think at the first install I still had 3.6.1 version open and only closed it when forced to do so.

**Comment by zeiseiwogn** [comment]
I am using Win7 x64 with .NET Framework 4.6.1 and updating Terminals from 4.0.0 to 4.0.1.
Now i am have made a repair installation of .NET Framework 4.6.2 and now it works!

Thanks a lot for support!
