### ISSUE TITLE
256 color support over SSH

### ISSUE THREAD

**Issue by willemdh** [Terminals-Origin/Terminals#74]
Is it possible in 'Terminals' to have 256 color support over ssh?

**Comment by Lillecarl** [comment]
If you compile HEAD you should see Terminals is now using Putty for SSH instead of a builtin version.

**Comment by willemdh** [comment]
@Lillecarl Sorry for the probably stupid question, but how can I 'compile HEAD'? Also while I tested ssh access to one of my VPS, I keep getting "the passphrase is wrong" error. But I can't find any place in the connection proprties where I can set a pasphrasefor my key. Nor does it seem to work keys loaded with Pageant. 

Thanks for the help.

**Comment by Lillecarl** [comment]
[Debug.zip](https://github.com/Terminals-Origin/Terminals/files/1326667/Debug.zip)
I uploaded the lastest development version for you here now (Beware of downloading .exe files from strangers though).

Try and see if you think SSH works better in this version.

(This is an unstable debug build, but it's useful for at least testing until @jirkapok deems Putty stable enough to release it 😄 )

**Comment by willemdh** [comment]
@Lillecarl Tested it, 256 colors are good. SSH authentication with Pageant works too.
I'll wait for new release. Using Conemu with Babun atm which works fine, but the favourite manager (tasks) is not very good.
