### ISSUE TITLE
NLA and SSO

### ISSUE THREAD

**Issue by Chrisnet46** [Terminals-Origin/Terminals#93]
Hi everyone,

I'm using Terminals for nearly eight years and today I can't open a session in console mode to a new RDS server with NLA enabled on the server. This is the first time NLA is enabled on one of our servers.

Since I run Terminals with a limited privileges account, I need to enter new credential with admin privileges but the logon screen never appears and I got an access denied message (probably because of the  limited privileges account trying to open a console mode session).

When I use mstsc.exe /admin, I do have the option to prompt for new credentials. Can I get the same option with Terminals with NLA enabled server ?

Thank you for your help.

Chris

**Comment by jirkapok** [comment]
Did you have a look at Favorite properties in Security Group? There is a NLA checkbox.

**Comment by brentlightsey** [comment]
@jirkapok is referring to this setting, I believe. After setting it for my connection, I was able to log into my server that required network level authentication.
![image](https://user-images.githubusercontent.com/651232/60525592-49efa800-9cb4-11e9-925c-2be8833fa714.png)

**Comment by Chrisnet46** [comment]
I do have this setting in place but I have to right click and choose "connect as" in order to open the session,  if I double click on the favorite, nothing happens.
