### ISSUE TITLE
Minimize Terminal 4.0.1 - Closes Terminals

### ISSUE THREAD

**Issue by TomDaria** [Terminals-Origin/Terminals#96]
To whom it may concern.

After successfully launching Terminals 4.0.1, I then connect to a remote server just fine.
But if I minimize my terminal window, Terminals shut down and I've lost my Terminals window and any connections underneath it.

Is there any way to prevent this?

Thanks
Tom

**Comment by DevinSharp** [comment]
Hi Tom,

I thought I had the same problem but noticed Terminals was actually minimizing to the system tray.

It looks like they defaulted on a couple of new(?) features.

In Options -> Interface -> System Tray, verify the "Minimize To Tray" box ix unchecked.

I also went to Startup & Shutdown -> Startup and checked the option for "Allow a single instance...."

**Comment by TomDaria** [comment]
That worked.  Many thanks.
Have a great day.
Saved me a bunch of headaches.
Tom
