### ISSUE TITLE
How to i run the tests?

### ISSUE THREAD

**Issue by Lillecarl** [Terminals-Origin/Terminals#97]
Regarding my PR, how do i run the tests? It's a class project so i can't launch it on it's own.

Sorry for being stupid, never done stuff like that before =)

**Comment by jirkapok** [comment]
Using Visual studio tools: Compile, and from menu Tests open test explorer, there are run and debug buttons.
Using Resharper, similar menu or right click on project and select run all tests.

**Comment by Lillecarl** [comment]
Thanks 😀
